### ISSUE TITLE
[ALIP] 开源产品项目 GameFi 管理

### ISSUE THREAD

**Issue by icepy** [coset-io/ALIP#2]
## 标题
 
**细分垂直领域的 GameFi 管家**

GameFi stewards in vertical segments

## 摘要

目前不管是 [https://zapper.fi/zh](https://zapper.fi/zh) 或 [https://debank.com/](https://debank.com/) 都是大而全的资产追踪和管理应用，随着 GameFi 的增长，玩家/公会，需要一个专注的资产追踪和管理应用来更方便的进行管理，观察。

Currently, both [https://zapper.fi/zh](https://zapper.fi/zh) or [https://debank.com/](https://debank.com/) are big and A complete asset tracking and management application, with the growth of GameFi, players/guilds need a dedicated asset tracking and management application for more convenient management and observation.

## 动机

由于个人是 treasure dao 的玩家，很需要有这样一个工具，可以观察，分析，管理自己的游戏地址

im treasure dao players, it is very necessary to have such a tool that can observe, analyze and manage their own game addresses

## 详细说明

目前 treasure dao 生态的游戏已经初步具备，玩家很希望能直观的看到，投入的成本，每个月能收获多少利润，以及什么时候回本（未来获利报税），我初步的设想是基于 treasure dao 来完成这个应用的 mvp 版本，主要支持两款游戏：[https://bridgeworld.treasure.lol/](https://bridgeworld.treasure.lol/) 和 [https://www.talesofelleria.com/](https://www.talesofelleria.com/)，它们都在 arbitrum 上。

At present, the game of the treasure dao ecosystem has been preliminarily available. Players hope to intuitively see the cost of investment, how much profit can be harvested each month, and when to pay back the cost (profit tax return in the future). My initial idea is based on treasure dao to complete the mvp version of this application, which mainly supports two games: [https://bridgeworld.treasure.lol/](https://bridgeworld.treasure.lol/) and [https://www.talesofelleria.com /](https://www.talesofelleria.com/), they are all on arbitrum.

初步设想这个应用主要有如下几项：

- 以游戏项目为主维度，以地址为子维度
- 允许玩家设置投入的成本
- 分析玩家打金数据
- 提供每月/年的打金数据账单
  - 利润
  - 增长

Preliminary assumptions about this application mainly include the following:

- Take the game item as the main dimension and the address as the sub-dimension
- Allows players to set the cost of inputs
- Analyze player gold data
- Provide monthly/yearly billing data bill
   - Profit
   - Growth

提供开源版本，因此不提供 website 的预览，但需要设计应用运行的配置方式（方便），让开发者可以在本机自行配置（本机服务，本机数据库存储等）

Provides an open source version, so it does not provide a preview of the website, but it is necessary to design the configuration method of application running (convenient), so that developers can configure themselves on the machine (native service, native database storage, etc.)

### 人员

1 人

- 前端工程师
- 后端工程师

### 费用

预期研发周期为 4 个月，月初支付

The expected R&D cycle is 4 months, with payment at the beginning of the month

人员的费用：

- 1人/月的费用需要 3676 USD

以太坊地址：0x8Ec882E845f60C7c0a65dCE55982a0139A65DFE7

## 风险

暂无风险

## 时间点

预期4个月内交付一个可用的开发者版本，开发者可以自行配置在本机运行此应用。

An available developer version is expected to be delivered within 4 months, and developers can configure and run the application locally.

第一月：

- 设计产品原型图
- 研究区块的数据分析方法
- 设计表结构
- 研究实现的方式

第二月

- 完成后端的开发工作
- 完成部分前端的开发工作

第三月

- 完成前端的开发工作
- 编写开源的手册和文档

第四个月

- 完成测试
- 留有一些 buff

First month:

- Design product prototypes
- Research block data analysis methods
- Design table structure
- Research the way it is implemented

second month

- Complete back-end development work
- Completed some front-end development work

third month

- Complete front-end development work
- Write open source manuals and documentation

fourth month

- complete test
- reserve some space for unknown problems

**Comment by luckyyang** [comment]
3,676USDT for the first month is sent

https://etherscan.io/tx/0x652acc6b782286229ef54a9d429c3ca905d21940f2b9fbe8d03c303f436ea983

**Comment by luckyyang** [comment]
3,676USDT for 2nd month is sent

https://etherscan.io/tx/0x687c30a900f8f2d675a18b651b2d4728edb9a3576dbe13813215d6e7ce868994

**Comment by icepy** [comment]
2672 USDT sent to Yiko

https://github.com/Antalpha-Labs/ledger/issues/6

**Comment by luckyyang** [comment]
This grant is finished, introduction post is here: https://mirror.xyz/icepy.eth/AITM8ZsYGVlV-eaNZZaP0fF1eFu6kiqlOX8HVwFpLEM
